#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --randomize --bg-max ~/Pictures/feh &
~/.config/polybar/hack/launch.sh

# Workspaces
bspc monitor -d I II III IV V

# Misc
bspc config focused_border_color "#8009e2"
bspc config border_width         3
bspc config window_gap           6

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

