background {
    monitor =
    path = screenshot          # or path to an image
    blur_passes = 2
}

input-field {
    monitor =
    size = 250, 50
    position = 0, -80
    halign = center
    valign = center
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    rounding = 8
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 90
    position = 0, 80
    halign = center
    valign = center
}
